server:
  port: 8088
  servlet:
    context-path: /api/myblog-service
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/myblog?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.server.blog.*.*.dao
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: false
      #删除
      logic-delete-value: 1
      #不删除
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true